// <auto-generated />
namespace IdeaManMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IdeaEntry_Dates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdeaEntry_Dates));
        
        string IMigrationMetadata.Id
        {
            get { return "201511231302431_IdeaEntry_Dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
